# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

[package]
name = "demikernel"
version = "1.0.16"
authors = ["Microsoft Corporation"]
edition = "2021"
description = "Kernel-Bypass LibOS Architecture"
readme = "README.md"
homepage = "https://aka.ms/demikernel"
repository = "https://github.com/demikernel/demikernel"
license-file = "LICENSE.txt"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/rust/lib.rs"

[dependencies]
arrayvec = "0.7.2"
anyhow = "1.0.64"
libc = "0.2.132"
rand = { version = "0.8.5", features = ["small_rng"] }
yaml-rust = "0.4.5"
log = "0.4.17"
nix = "0.25.0"

inetstack = { git = "https://github.com/demikernel/inetstack", rev = "e055397fa7b6fa688314db774f5054d830e17a1d" }

[[test]]
name = "sga"
path = "tests/rust/sga.rs"

[[example]]
name = "udp-push-pop"
path = "examples/rust/udp-push-pop.rs"

[[example]]
name = "udp-ping-pong"
path = "examples/rust/udp-ping-pong.rs"

[[example]]
name = "tcp-push-pop"
path = "examples/rust/tcp-push-pop.rs"

[[example]]
name = "tcp-ping-pong"
path = "examples/rust/tcp-ping-pong.rs"


[features]
default = [ "catnap-libos" ]
catnap-libos = [ ]
catpowder-libos = [ ]
catcollar-libos = [ "inetstack/liburing" ]
catnip-libos = [ "inetstack/libdpdk" ]
mlx4 = ["inetstack/libdpdk", "inetstack/mlx4"]
mlx5 = ["inetstack/libdpdk", "inetstack/mlx5"]
profiler = [ "inetstack/profiler" ]


[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
rpath = false
