[package]
name = "demikernel"
version = "1.0.2"
edition = "2018"
authors = ["Microsoft Corporation"]
description = "Kernel-Bypass LibOS Architecture"
homepage = "https://aka.ms/demikernel"
repository = "https://github.com/demikernel/demikernel"
readme = "README.md"
license-file = "LICENSE.txt"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
arrayvec = "0.7.2"
anyhow = "1.0.57"
libc = "0.2.126"
rand = { version = "0.8.5", features = ["small_rng"] }
yaml-rust = "0.4.5"
log = "0.4.17"
nix = "0.23.1"
socket2 = { version = "0.4.4", features = ["all"] }
cfg-if = "1.0.0"

inetstack = { git = "https://github.com/demikernel/inetstack", rev = "a917c973064ffebcce6f453c76b141371d4aa51a" }
scheduler = { git = "https://github.com/demikernel/scheduler", rev = "9583bfd7ceae1c0ee62cef0e69b37752d8475ccc" }
dpdk-rs = { git = "https://github.com/demikernel/dpdk-rs", rev = "a53027171bf38da8d776235693458acdcf979632", optional = true }
perftools = { git = "https://github.com/demikernel/perftools", rev = "02f07ad28218c182bbf82e5f8eaf22f7de3f34c6", optional = true }
runtime = { git = "https://github.com/demikernel/runtime", rev = "a6551e787cbeeecbac95195626306a82cb37e119" }
liburing = { git = "https://github.com/demikernel/liburing-rs", rev = "0b9d8a681f123adb60367ff72aa6e3cc198b3dd6", optional = true }

[[test]]
name = "sga"
path = "tests/rust/sga.rs"

[[test]]
name = "pushpop"
path = "tests/rust/pushpop.rs"

[[test]]
name = "pingpong"
path = "tests/rust/pingpong.rs"

[features]
default = [  ]
catnap-libos = [ ]
catpowder-libos = [ ]
catcollar-libos = [ "liburing" ]
catnip-libos = [ "dpdk-rs" ]
mlx4 = ["dpdk-rs", "dpdk-rs/mlx4"]
mlx5 = ["dpdk-rs", "dpdk-rs/mlx5"]
profiler = [ "perftools", "inetstack/profiler" ]


[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
rpath = false