[package]
name = "demikernel"
version = "1.0.4"
edition = "2018"
authors = ["Microsoft Corporation"]
description = "Kernel-Bypass LibOS Architecture"
homepage = "https://aka.ms/demikernel"
repository = "https://github.com/demikernel/demikernel"
readme = "README.md"
license-file = "LICENSE.txt"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
arrayvec = "0.7.2"
anyhow = "1.0.57"
libc = "0.2.126"
rand = { version = "0.8.5", features = ["small_rng"] }
yaml-rust = "0.4.5"
log = "0.4.17"
nix = "0.24.1"

inetstack = { git = "https://github.com/demikernel/inetstack", rev = "b0dcd1f9643e355ca16e24ef5dfe24b35cd788e2" }
perftools = { git = "https://github.com/demikernel/perftools", rev = "10740b3c46440f4eef740c401d8fd2385998c16a", optional = true }
runtime = { git = "https://github.com/demikernel/runtime", rev = "76692aa98f56b369b4e0783f5d5a4edf94c3ee86" }

[[test]]
name = "sga"
path = "tests/rust/sga.rs"

[[test]]
name = "pushpop"
path = "tests/rust/pushpop.rs"

[[test]]
name = "pingpong"
path = "tests/rust/pingpong.rs"

[features]
default = [ ]
catnap-libos = [ ]
catpowder-libos = [ ]
catcollar-libos = [ "runtime/liburing" ]
catnip-libos = [ "runtime/libdpdk" ]
mlx4 = ["runtime/libdpdk", "runtime/mlx4"]
mlx5 = ["runtime/libdpdk", "runtime/mlx5"]
profiler = [ "perftools", "inetstack/profiler" ]


[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
rpath = false