# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

[package]
name = "demikernel"
version = "1.0.17"
authors = ["Microsoft Corporation"]
edition = "2021"
description = "Kernel-Bypass LibOS Architecture"
readme = "README.md"
homepage = "https://aka.ms/demikernel"
repository = "https://github.com/demikernel/demikernel"
license-file = "LICENSE.txt"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/rust/lib.rs"

[dependencies]
arrayvec = "0.7.2"
async-trait = "0.1.57"
anyhow = "1.0.64"
bit-iter = "1.1.1"
byteorder = "1.4.3"
cfg-if = "1.0.0"
crc = "3.0.0"
crossbeam-channel = "0.5.6"
derive_more = "0.99.17"
eui48 = "1.1.0"
flexi_logger = "0.23.1"
float_duration = "0.3.3"
futures = "0.3.24"
libc = "0.2.132"
log = "0.4.17"
nix = "0.25.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
rand = { version = "0.8.5", features = ["small_rng"] }
slab = "0.4.7"
yaml-rust = "0.4.5"
x86 = "0.51.0"

liburing = { git = "https://github.com/demikernel/liburing-rs", rev = "780827ee3f805d94f9909bd47cd925ee8476a64b", optional = true}
dpdk-rs = { git = "https://github.com/demikernel/dpdk-rs", rev = "7d75ce6db61351d2a06fa3d84bd0af3ec017166d", optional = true }

[[test]]
name = "tcp"
path = "tests/rust/tcp.rs"

[[test]]
name = "udp"
path = "tests/rust/udp.rs"

[[test]]
name = "sga"
path = "tests/rust/sga.rs"

[[example]]
name = "udp-push-pop"
path = "examples/rust/udp-push-pop.rs"

[[example]]
name = "udp-ping-pong"
path = "examples/rust/udp-ping-pong.rs"

[[example]]
name = "tcp-push-pop"
path = "examples/rust/tcp-push-pop.rs"

[[example]]
name = "tcp-ping-pong"
path = "examples/rust/tcp-ping-pong.rs"


[features]
default = [ "catnap-libos" ]
catnap-libos = [ ]
catpowder-libos = [ ]
catcollar-libos = [ "liburing" ]
catnip-libos = [ "libdpdk" ]
libdpdk = [ "dpdk-rs" ]
mlx4 = [ "dpdk-rs/mlx4" ]
mlx5 = [ "dpdk-rs/mlx5" ]
profiler = [  ]


[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
rpath = false
