[package]
name = "demikernel"
version = "1.0.1"
edition = "2018"
authors = ["Microsoft Corporation"]
description = "Kernel-Bypass LibOS Architecture"
homepage = "https://aka.ms/demikernel"
repository = "https://github.com/demikernel/demikernel"
readme = "README.md"
license-file = "LICENSE.txt"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
arrayvec = "0.7.2"
anyhow = "1.0.57"
clap = "3.0.13"
libc = "0.2.116"
rand = { version = "0.8.4", features = ["small_rng"] }
yaml-rust = "0.4.5"
log = "0.4.14"
nix = "0.23.1"
socket2 = { version = "0.4.1", features = ["all"] }
cfg-if = "1.0.0"

inetstack = { git = "https://github.com/demikernel/inetstack", rev = "39e99b46b7ee2376a5e6a4e39a0568990d932a2b" }
scheduler = { git = "https://github.com/demikernel/scheduler", rev = "9583bfd7ceae1c0ee62cef0e69b37752d8475ccc" }
dpdk-rs = { git = "https://github.com/demikernel/dpdk-rs", rev = "f6619d5313fc224e6bf8620df7485517efea0e39", optional = true }
perftools = { git = "https://github.com/demikernel/perftools", rev = "02f07ad28218c182bbf82e5f8eaf22f7de3f34c6", optional = true }
runtime = { git = "https://github.com/demikernel/runtime", rev = "b1d6e4c2f3eebb35c582e8b24c0d99e5987e9a2b" }
liburing = { git = "https://github.com/demikernel/liburing-rs", rev = "e80e6238f47498b7c4e37194e896a39713c61cd9", optional = true }

[[test]]
name = "sga"
path = "tests/rust/sga.rs"

[[test]]
name = "pushpop"
path = "tests/rust/pushpop.rs"

[[test]]
name = "pingpong"
path = "tests/rust/pingpong.rs"

[features]
default = [  ]
catnap-libos = [ ]
catpowder-libos = [ ]
catcollar-libos = [ "liburing" ]
catnip-libos = [ "dpdk-rs" ]
mlx4 = ["dpdk-rs", "dpdk-rs/mlx4"]
mlx5 = ["dpdk-rs", "dpdk-rs/mlx5"]
profiler = [ "perftools", "inetstack/profiler" ]


[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
rpath = false