# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

[package]
name = "demikernel"
version = "1.0.11"
authors = ["Microsoft Corporation"]
edition = "2021"
description = "Kernel-Bypass LibOS Architecture"
readme = "README.md"
homepage = "https://aka.ms/demikernel"
repository = "https://github.com/demikernel/demikernel"
license-file = "LICENSE.txt"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/rust/lib.rs"

[dependencies]
arrayvec = "0.7.2"
anyhow = "1.0.59"
libc = "0.2.127"
rand = { version = "0.8.5", features = ["small_rng"] }
yaml-rust = "0.4.5"
log = "0.4.17"
nix = "0.24.2"

inetstack = { git = "https://github.com/demikernel/inetstack", rev = "448f1d542089d7dc2d3d7dc974583023ee7663d3" }
runtime = { git = "https://github.com/demikernel/runtime", rev = "8362132e2476fb7b0825b3f8ae976ded8a98b956" }

[[test]]
name = "sga"
path = "tests/rust/sga.rs"

[[test]]
name = "pushpop"
path = "tests/rust/pushpop.rs"

[[test]]
name = "pingpong"
path = "tests/rust/pingpong.rs"

[features]
default = [ ]
catnap-libos = [ ]
catpowder-libos = [ ]
catcollar-libos = [ "runtime/liburing" ]
catnip-libos = [ "runtime/libdpdk" ]
mlx4 = ["runtime/libdpdk", "runtime/mlx4"]
mlx5 = ["runtime/libdpdk", "runtime/mlx5"]
profiler = [ "inetstack/profiler" ]


[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
rpath = false