[package]
name = "demikernel"
version = "1.0.3"
edition = "2018"
authors = ["Microsoft Corporation"]
description = "Kernel-Bypass LibOS Architecture"
homepage = "https://aka.ms/demikernel"
repository = "https://github.com/demikernel/demikernel"
readme = "README.md"
license-file = "LICENSE.txt"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
arrayvec = "0.7.2"
anyhow = "1.0.57"
libc = "0.2.126"
rand = { version = "0.8.5", features = ["small_rng"] }
yaml-rust = "0.4.5"
log = "0.4.17"
nix = "0.24.1"
cfg-if = "1.0.0"

inetstack = { git = "https://github.com/demikernel/inetstack", rev = "2410e40245a3f04e84b1c3a6b5d08e633d2dd2fa" }
scheduler = { git = "https://github.com/demikernel/scheduler", rev = "7bd71378a6121e33bf55f79248f2a2a812815d6e" }
perftools = { git = "https://github.com/demikernel/perftools", rev = "10740b3c46440f4eef740c401d8fd2385998c16a", optional = true }
runtime = { git = "https://github.com/demikernel/runtime", rev = "7d9c21f9b48036e690964cd64bc4c75abc7b0255" }

[[test]]
name = "sga"
path = "tests/rust/sga.rs"

[[test]]
name = "pushpop"
path = "tests/rust/pushpop.rs"

[[test]]
name = "pingpong"
path = "tests/rust/pingpong.rs"

[features]
default = [  ]
catnap-libos = [ ]
catpowder-libos = [ ]
catcollar-libos = [ "runtime/liburing" ]
catnip-libos = [ "runtime/libdpdk" ]
mlx4 = ["runtime/libdpdk", "runtime/mlx4"]
mlx5 = ["runtime/libdpdk", "runtime/mlx5"]
profiler = [ "perftools", "inetstack/profiler" ]


[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
rpath = false