[profile.release]
lto = true
overflow-checks = true
debug = true

[profile.bench]
lto = true
overflow-checks = true
debug = true

[workspace]
members = [
    "catnip",
    "catnip_libos",
    "experiments",
]
